# Generated by Django 5.1.6 on 2025-03-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_about_alter_profile_options_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
