# Generated by Django 5.1.6 on 2025-03-13 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255, verbose_name='site title')),
                ('tagline', models.CharField(help_text='In a few words, explain what this site is about. Example: “Just another WordPress site.”', max_length=255, verbose_name='tagline')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='keywords')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='bio')),
                ('site_icon', models.ImageField(help_text='The Site Icon is what you see in browser tabs, bookmark bars, and within the WordPress mobile apps. It should be square and at least 512 by 512 pixels.', upload_to='logo_pics', verbose_name='site icon')),
                ('logo', models.ImageField(upload_to='logo_pics', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique_for_date='post_date')),
                ('content', models.TextField(verbose_name='content')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='post date')),
                ('post_update', models.DateTimeField(auto_now=True, verbose_name='post update')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('body', models.TextField(verbose_name='body')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='comment date')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-comment_date'],
            },
        ),
    ]
