# Generated by Django 5.1.6 on 2025-03-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'About Information',
            },
        ),
    ]
