# Generated by Django 5.1.6 on 2025-03-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255)),
                ('Tagline', models.CharField(max_length=255)),
                ('site_icon', models.ImageField(upload_to='logo_pics', verbose_name='site icon')),
                ('logo', models.ImageField(upload_to='logo_pics', verbose_name='logo')),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='short_description',
        ),
    ]
