# Generated by Django 5.1.6 on 2025-03-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_setting_rename_full_description_about_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting'},
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='Tagline',
            new_name='tagline',
        ),
    ]
