# Generated by Django 5.1.6 on 2025-03-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_setting_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bio'),
        ),
    ]
